export interface IColorToken {
	"white": string,
	"black": string,

	"brand1": string,
	"brand10": string,
	"brand20": string,
	"brand30": string,
	"brand40": string,
	"brand50": string,
	"brand60": string,
	"brand70": string,
	"brand80": string,
	"brand90": string,
	"brand100": string,

	"grayScale1": string,
	"grayScale5": string,
	"grayScale10": string,
	"grayScale20": string,
	"grayScale30": string,
	"grayScale40": string,
	"grayScale50": string,
	"grayScale60": string,
	"grayScale70": string,
	"grayScale80": string,
	"grayScale90": string,
	"grayScale100": string,

	"positive1": string,
	"positive10": string,
	"positive20": string,
	"positive30": string,
	"positive40": string,
	"positive50": string,
	"positive60": string,
	"positive70": string,
	"positive80": string,
	"positive90": string,
	"positive100": string,

	"warning1": string,
	"warning10": string,
	"warning20": string,
	"warning30": string,
	"warning40": string,
	"warning50": string,
	"warning60": string,
	"warning70": string,
	"warning80": string,
	"warning90": string,
	"warning100": string,

	"negative1": string,
	"negative10": string,
	"negative20": string,
	"negative30": string,
	"negative40": string,
	"negative50": string,
	"negative60": string,
	"negative70": string,
	"negative80": string,
	"negative90": string,
	"negative100": string,
}

export interface IColor {
	light: IColorToken,
	dark: IColorToken
}